# Generated by Django 6.0.7 on 2026-07-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'hôtel")),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Numéro de téléphone')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix par nuit')),
                ('currency', models.CharField(choices=[('XOF', 'F XOF'), ('EUR', '€ EUR'), ('USD', '$ USD')], default='XOF', max_length=3, verbose_name='Devise')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
